add lesson1
miklashevich/Lesson1 pull request #1
Opened 2021-01-30 10:22 UTC by miklashevich

2021-02-01 21:33 UTC, AntonShtabnoy requested changes

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        n = 87;
В данном случае нет смысла сначала просто объявлять переменную и потом в след строке инициализировать ее - лучше сразу int n = 78;

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if (n/100>=1 & n/100<=9) {
Обрати внимание на форматирование if (n / 100 >= 1 & n / 100 <= 9) - везде должны быть пробелы между символами. Автоформатирование делается сочетанием клавиш ctrl+alt+L

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if (n/100>=1 & n/100<=9) {
Почитай про различие & и && https://ru.stackoverflow.com/questions/938756/%D0%92-%D1%87%D0%B5%D0%BC-%D1%80%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%B8-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-java

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if (n/100>=1 & n/100<=9) {
Как можно проверить трехзначость через одно условие?

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if(n%2==0) {
форматирование

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if(n%10==7) {
форматировние

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/Main.java
> +        System.out.println("Hi!");
Команда в консоли должна выглядеть java -cp /home Main Privet
И вот эту строку(Privet) что я передаю в конце должна вывести программа на экран.

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/NumberPrinter.java
> +        System.out.println((x %100-((x % 100/10)*10))*1000+((x % 100/10)*100)+((x % 1000/100)*10)+(x/1000));
Лучше каждую цифру записать отдельной переменной так легче читать - и потом можно будет их переиспользовать - если будет расширенное условие

2021-02-01 21:33 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/СircleAndRectangle.java
> +            System.out.println("Отверстие со сторонами" +" " + a +" " + "и" +" " + b  +" " + "Нельзя закрыть картонкой с радиусом" + " "  +r);
Как я говорил на уроку в if лучше использовать {}

2021-02-01 21:53 UTC, AntonShtabnoy requested changes

2021-02-01 21:53 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/СircleAndRectangle.java
> +          int r=38;
А стороны могут быть дробными?

2021-02-02 07:02 UTC, miklashevich commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if(n%10==7) {
что значит форматирование?

2021-02-02 07:03 UTC, miklashevich commented on src/by/miklashevich/lesson1/Main.java
> +        System.out.println("Hi!");
это не ответ на таску, это просто проба была залить что то на гитхаб), ответ про команду в консоли я отправил скрином

2021-02-02 13:59 UTC, miklashevich commented on src/by/miklashevich/lesson1/NumberPrinter.java
> +        System.out.println((x %100-((x % 100/10)*10))*1000+((x % 100/10)*100)+((x % 1000/100)*10)+(x/1000));
ок, в задании было непонятно написано

2021-02-02 13:59 UTC, miklashevich commented on src/by/miklashevich/lesson1/NumberPrinter.java
> +        System.out.println((x %100-((x % 100/10)*10))*1000+((x % 100/10)*100)+((x % 1000/100)*10)+(x/1000));
вернее не было написано вообще

2021-02-02 14:25 UTC, miklashevich commented on src/by/miklashevich/lesson1/СircleAndRectangle.java
> +          int r=38;
да, я переделал уже

2021-02-02 14:25 UTC, miklashevich commented on src/by/miklashevich/lesson1/СircleAndRectangle.java
> +            System.out.println("Отверстие со сторонами" +" " + a +" " + "и" +" " + b  +" " + "Нельзя закрыть картонкой с радиусом" + " "  +r);
исправил

2021-02-07 21:22 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if(n%10==7) {
Обрати внимание на форматирование if (n / 100 >= 1 & n / 100 <= 9) - везде должны быть пробелы между символами. Автоформатирование делается сочетанием клавиш ctrl+alt+L

2021-02-07 21:22 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/EvenOdd.java
> +        if(n%10==7) {
Читай внимательнее комменты

2021-02-07 21:23 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/Main.java
> +        System.out.println("Hi!");
На уроке обсуждали эту задачу

2021-02-07 21:24 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/NumberPrinter.java
> +        System.out.println((x %100-((x % 100/10)*10))*1000+((x % 100/10)*100)+((x % 1000/100)*10)+(x/1000));
Это надо продумать самому - не всегда в техническом задании все будет описано - надо думать логически, продумывать как это будет дальше использоваться

2021-02-07 21:28 UTC, AntonShtabnoy requested changes

2021-02-07 21:28 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/FourDigitNumber.java
> +                ;
Точка с запятой ставится на той же строке где и прописаны операторы

2021-02-07 21:28 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/СircleAndRectangle.java
> +          double a=50.5;
Форматирование  double a = 50.5; - оператор присваивания не слепливать
Пользуйся форматирование среды разработки - клавиши прописывал

2021-02-08 10:30 UTC, merged