Lesson 3
miklashevich/Lesson1 pull request #6
Opened 2021-02-08 07:13 UTC by miklashevich

2021-02-08 10:43 UTC, AntonShtabnoy requested changes

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson1/Arguments.java
> +package by.miklashevich.lesson1;
Ты наверно создаешь новую ветку с lesson1 ветки, а не с мастера. Так как у тебя в ветке lesson3 задания из пред дз

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson2/task4.java
> +public class task4 {
Название класса должно пишется с большой буквы

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson3/task1.java
> +        int max = myArray[0]; // Присваиваем перем. max значение нулевого элемента, пока считаем что это макс.значение в массиве
А что если массив пустой? - 0-й ячейки не будет, лучше присваивать минимальное значение для данного типа данных

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson3/task3.java
> +//
Форматирование - лишние пробелы, комментарии просто по коду в 17 строке. Очень грязно - смотреть не очень

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson3/task3.java
> +//
Почему нельзя сделать цикл до 256 включительно?

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson3/task6.java
> +           d = d * 1.1; // прошел в i день
а если процент изменится? решение сломается - лучше процент вынести в переменную. Так в дальнейшем не надо будет лазить по коду и искать где нужно мне что-то изменить. Просто поменял значение переменной, которая отвечает за процент

2021-02-08 10:43 UTC, AntonShtabnoy commented on src/by/miklashevich/lesson3/task8.java
> +     for (int i= 10; i <= n; i++) { // цикл до значениея n c шагом +1
Лучше i присваивать начальное значение через переменную, потому что если я захочу изменить входные параметры, я должен менять только их, а сам алгоритм оставаться неизменным

2021-02-10 10:48 UTC, miklashevich commented on src/by/miklashevich/lesson1/Arguments.java
> +package by.miklashevich.lesson1;
я в idea создаю новую ветку (по названию урока), и оттуда уже пушу с комитами в github (предварительно создав new branch в idea)

2021-02-10 10:50 UTC, miklashevich commented on src/by/miklashevich/lesson1/Arguments.java
> +package by.miklashevich.lesson1;
![Screenshot_32](https://user-images.githubusercontent.com/35031208/107500118-db204380-6ba6-11eb-8b9d-4a29d6775316.jpg)

2021-02-10 18:33 UTC, miklashevich commented on src/by/miklashevich/lesson3/task3.java
> +//
исправил

2021-02-10 18:43 UTC, miklashevich commented on src/by/miklashevich/lesson3/task6.java
> +           d = d * 1.1; // прошел в i день
исправил

2021-02-10 18:45 UTC, miklashevich commented on src/by/miklashevich/lesson2/task4.java
> +public class task4 {
исправлю в след.заданиях, сейчас если исправляю, то не могу запушить на гитхаб, т.к.папку не находит

2021-02-10 18:48 UTC, miklashevich commented on src/by/miklashevich/lesson3/task1.java
> +        int max = myArray[0]; // Присваиваем перем. max значение нулевого элемента, пока считаем что это макс.значение в массиве
я не очень понял )

2021-02-14 19:41 UTC, merged